# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pybuilder PreForM.py==1.1.2
    - name: Test build package
      run: |
        pyb
    - name: Test install package on Linux/macOS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      run: |
        cd release
        cd $(ls -d FoBiS-*)
        python setup.py install
    - name: Test install package on Windows
      if: startsWith(runner.os, 'Windows')
      run: |
        cd release
        cd $(ls -Directory FoBiS-*)
        python setup.py install
    - name: Test FoBiS.py -h
      shell: bash
      run: |
        python --version
        pip list
        FoBiS.py -v
        FoBiS.py -h
    - name: Prepare GFortran macOS
      if: startsWith(runner.os, 'macOS')
      run: |
          ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          which gfortran-9
          which gfortran
    # - name: Unit test on macOS
    #   if: startsWith(runner.os, 'macOS')
    #   continue-on-error: true
    #   run: |
    #     cd src/unittest/python
    #     ./suite_tests.py
    - name: Unit test on Linux
      if: startsWith(runner.os, 'Linux')
      run: |
        cd src/unittest/python
        ./suite_tests.py
